select FT.VALUE    FOREST_TYPE_CD,
       FT.MEANING  FOREST_TYPE,
       FTG.VALUE   FOREST_TYPE_GROUP_CD,
       FTG.MEANING FOREST_TYPE_GROUP
  from FS_FIADB.REF_FOREST_TYPE_GROUP FTG, FS_FIADB.REF_FOREST_TYPE FT
 where FT.TYPGRPCD = FTG.VALUE
